### PR TITLE
link to bmlt-enabled, spelling and add timezone api req. to google api

### PR DESCRIPTION
**Pull request by pjaudiomv**
wondering if we can link yap.bmlt.app to bmlt-enabled/yap otherwise youll just have to make sure to try to keep your fork at radius314/yap up to date.

### CODE REVIEW

**Comment by pjaudiomv** [comment]
ahhh ok thanks ill take a look

**Comment by radius314** [comment]
This does not seem right

**Comment by pjaudiomv** [comment]
ok so if this one doesn't build we may want to see about forking just the docs and point our theme to that fork, currently were pointing to the author at https://github.com/pmarsceill/just-the-docs and they made some changes that was breaking our build.

**Comment by radius314** [comment]
fork the theme to bmlt-enabled

**Comment by pjaudiomv** [comment]
oh shoot yes theres extra files that arent needed in here as i ran the site locally so i need to revert that last commit

**Comment by radius314** [comment]
Either that, are they tagging releases?  Possible to point to a theme in the yaml file?

**Comment by radius314** [comment]
Theme tag

**Comment by radius314** [comment]
Revert and add the unwanted path to gitignore

**Pull request merged**
