### PR TITLE
get rid of DS_Store once and for all

### PR DESCRIPTION
**Pull request by pjaudiomv**
I added a global ignore for .DS_Store on my system hopefully this wont be a problem anymore for yap or other repos

### CODE REVIEW

**Comment by pjaudiomv** [comment]
this has been a plaque to my repos, didn't realize there was a global ignore option till now

**Comment by radius314** [comment]
global ignore won't actually help other people on repos, you still need to add it to .gitignore on a per repo basis.

**Comment by pjaudiomv** [comment]
ok got it, it helps me, but still need to add to .gitignore

**Comment by radius314** [comment]
correct

**Pull request merged**
