### PR TITLE
fix for No map link on SMS #254

### PR DESCRIPTION
**Pull request by pjaudiomv**
this must not have been merged back in after adding feature. not sure if this is how we want to fix it, but I have tested the following ways and works fine.
1. with include_map_link set but not include_location_text.
2. with include_location_text but not include_map_link set.
3. both include_map_link and include_location_text set.
4. neither include_location_text and include_map_link set.

### CODE REVIEW

**Comment by brustar64** [comment]
I'd like option 3 please

**Comment by pjaudiomv** [comment]
You can do either or using those settings. Those are just all the ways I tested to verify the change  works as expected.

**Comment by brustar64** [comment]
I'm not sure what I'm missing here - still not getting a map link on the sms for Version 3...
static $include_map_link = true;

**Comment by pjaudiomv** [comment]
thats correct the map link isn't working. this is a pull request to fix that. this will be fixed in next release.

**Pull request merged**
