### PR TITLE
fix for status messages breaking login page on some servers #677

### PR DESCRIPTION
**Pull request by dgershman**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
just tested this on gyro with exclude error option and am now getting this error

<details>
  <summary>Laravel Error</summary>
```log
[previous exception] [object] (Twilio\\Exceptions\\ConfigurationException(code: 0): Credentials are required to create a Client at /var/www/gyro.sezf.org/zonal-yap/vendor/twilio/sdk/src/Twilio/Rest/Client.php:167)
[stacktrace]
#0 /var/www/gyro.sezf.org/zonal-yap/legacy/_includes/twilio-client.php(6): Twilio\\Rest\\Client->__construct()
#1 /var/www/gyro.sezf.org/zonal-yap/legacy/index.php(3): require_once('...')
#2 /var/www/gyro.sezf.org/zonal-yap/storage/framework/views/e483aff1d500c53cc4d484dd3a6487dd7cfe9d1a.php(2): require('...')
#3 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')
#4 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#5 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#6 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#7 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()
#8 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#9 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#10 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#11 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#12 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct()
#13 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()
#14 /var/www/gyro.sezf.org/zonal-yap/app/Http/Controllers/LegacyController.php(28): Illuminate\\Routing\\ResponseFactory->view()
#15 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\LegacyController->index()
#16 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#17 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#18 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#19 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#20 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#21 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#23 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#27 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#29 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#30 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#32 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#36 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#38 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#39 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#40 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#43 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#44 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#47 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#49 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#51 /var/www/gyro.sezf.org/zonal-yap/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#53 /var/www/gyro.sezf.org/zonal-yap/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#55 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#57 /var/www/gyro.sezf.org/zonal-yap/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#58 /var/www/gyro.sezf.org/zonal-yap/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#59 {main}
"}
```
</details>

**Comment by dgershman** [comment]
weird

**Comment by dgershman** [comment]
are you sure you copied all the files over correctly?

**Comment by dgershman** [comment]
did u make changes manually?

**Comment by pjaudiomv** [comment]
Ok I just cloned the branch and replaced the legacy directory. the screen loads and the status is green and says ok but if you click on it it returns

```json
{
"status":false,
"message":"Error: Undefined array key \"run_exclude_errors_check\""
}
```

**Comment by pjaudiomv** [comment]
I think were good now, it returns this but status is green and says ok

```json
{
"status":false,
"message":"Twilio Configuration Error: Credentials are required to create a Client",
"warnings":"",
"version":"4.2.5",
"build":"47469a5d23cf3adc7eb2f9fa0a6d01d9715acc91"
}
```

**Comment by dgershman** [comment]
Yes essentially that is the same behavior as on 4.2.0, before logging in.  The status should change after you login as a user that might inherit a good / present api key.

**Review by pjaudiomv — APPROVED** [review]

**Comment by pjaudiomv** [comment]
> I am going to make one more change

Ok 👌

**Comment by dgershman** [comment]
can you test this change?

**Comment by pjaudiomv** [comment]
> can you test this change?

Yea will test in a few mins, making some foods

**Comment by pjaudiomv** [comment]
just tested. that works great, thanks

**Review by pjaudiomv — APPROVED** [review]

**Pull request merged**
