### PR TITLE
yap doc updates point to bmlt-enabled

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
Yes I agree, I hadn't come up with anything. the simplest would be just have the readme just point to yap.docs and just have basic stuff in the readme

**Comment by pjaudiomv** [comment]
but as far as editing once and showing up in both places, not sure.

**Comment by radius314** [comment]
I wonder if GitHub respects symbolic links.

**Comment by pjaudiomv** [comment]
https://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links

**Comment by radius314** [comment]
Looks like we just have to delete the README in root https://help.github.com/articles/about-readmes/

**Comment by pjaudiomv** [comment]
couldn't we keep it and just include info on what the project is and why you may want to use it, etc. and then just include a link to point people to yap.bmlt.app for install info and more in depth docs

**Comment by radius314** [comment]
Sure

**Comment by pjaudiomv** [comment]
im just thinking of what would be a simple solution that makes sense.

**Comment by radius314** [comment]
Sounds good

**Pull request merged**
