### PR TITLE
configure pdo to stringify results for breaking change in php 8.1

### PR DESCRIPTION
**Pull request by jbraswell**

### CODE REVIEW

**Review by pjaudiomv — APPROVED** [review]

**Comment by dgershman** [comment]
what was the exact underlying issue that PDO caused?

**Comment by pjaudiomv** [comment]
With PHP 8.1 or grater, Integers and floats are returned using native PHP types instead of strings

**Comment by pjaudiomv** [comment]
https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.pdo.mysql

**Comment by pjaudiomv** [comment]
we hit this same issue with the root server

**Comment by jbraswell** [comment]
> should i basically update the container to 8.1 and then disable these flags and test when it's time to fix?

Yep, that's right.

**Pull request merged**
