### PR TITLE
admin enhancements

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
What's the bitwise stuff for

**Comment by radius314** [comment]
> What's the bitwise stuff for

There is a single integer database column.  As the "permissions" expand, that same field can be re-used over an over.   For example:

1 = Manage Users
2 = Manage Service Bodies
4 = View Only Service Bodies
8 = Manage Configuration.

These can then be summed together.  So let's say the user has the ability to Manage Service Bodies + Manage Configuration.  The sum would be 10.  

On the way out, you can decompose that to know which settings the user has.

**Comment by pjaudiomv** [comment]
ahh cool

**Comment by pjaudiomv** [comment]
this looks pretty good, I can test more tomorrow.

**Comment by pjaudiomv** [comment]
self password reset doesnt seem to be working, If i log in as a non admin and go to my profile and change password, hit save and log out. the new password does not work. i can see the hash in DB never changed either.

**Comment by radius314** [comment]
> self password reset doesnt seem to be working, If i log in as a non admin and go to my profile and change password, hit save and log out. the new password does not work. i can see the hash in DB never changed either.

fixed

**Pull request merged**
