### PR TITLE
best of both worlds

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
#189

**Comment by radius314** [comment]
worked on your MV use-case?

**Comment by pjaudiomv** [comment]
up no let me test that, good thinking

**Comment by pjaudiomv** [comment]
yup worked fine with MV too
`/yap-2.5.0/index.php?override_service_body_id=8&override_result_count_max=7&override_custom_query=%26services%5B%5D%3D8`

**Comment by radius314** [comment]
kewl

**Pull request merged**
