### PR TITLE
Mo migrations

### PR DESCRIPTION
**Pull request by dgershman**

### CODE REVIEW

**Review by pjaudiomv — APPROVED** [review]

**Comment by pjaudiomv** [comment]
Jft seems unhappy 🙁

**Comment by dgershman** [comment]
> Jft seems unhappy 🙁

The cert was renewed 3 days ago, maybe it's related.

**Comment by dgershman** [comment]
> > Jft seems unhappy 🙁
> 
> The cert was renewed 3 days ago, maybe it's related.

CurlException: SSL peer certificate or SSH remote key was not OK in...

**Comment by dgershman** [comment]
Ok figured it out.  When they renewed the cert, they forgot to add a SAN for `www.jftna.org`.  This may have broken everyone's JFT.  If your client handles meta redirect, then you'll be ok.

repro step:
```shell
21:33:13 › curl https://www.jftna.org/jft/
curl: (60) SSL: no alternative certificate subject name matches target host name 'www.jftna.org'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by dgershman** [comment]
```
*   Trying 103.26.143.152:443...
* Connected to www.jftna.org (103.26.143.152) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /usr/local/etc/openssl@1.1/cert.pem
*  CApath: none
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=jftna.org
*  start date: Oct 25 16:36:05 2022 GMT
*  expire date: Nov 26 16:36:04 2023 GMT
*  subjectAltName does not match www.jftna.org
* SSL: no alternative certificate subject name matches target host name 'www.jftna.org'
* Closing connection 0
```

**Comment by dgershman** [comment]
passing now

**Pull request merged**
