### PR TITLE
fix advisor link for login url

### PR DESCRIPTION
**Pull request by pjaudiomv**
im sure theres a better fix for this but the status advisor link on sign in admin page is broken

### CODE REVIEW

**Comment by dgershman** [comment]
You should be able to simply use the url function

**Comment by pjaudiomv** [comment]
I tried that and it was no bueno, ill try again

**Comment by pjaudiomv** [comment]
ok that totes works, not sure what i was doing wrong first time

**Comment by pjaudiomv** [comment]
> I tried that and it was no bueno, ill try again

I did have the echo statement first time around  :/

**Comment by dgershman** [comment]
So it did work or didn't?

**Comment by pjaudiomv** [comment]
> So it did work or didn't?

Yea it works

**Review by dgershman — APPROVED** [review]

**Pull request merged**
