### PR TITLE
not sure how to tag version

### PR DESCRIPTION
**Pull request by pjaudiomv**
so apparently that wasn't how you tag a version, however I'm not positive this is either

### CODE REVIEW

**Comment by radius314** [comment]
?

**Comment by pjaudiomv** [comment]
sorry, that build error you just emailed me was from this line actually in the _config.yml
`remote_theme: "bmlt-enabled/just-the-docs", "~> 0.2.0"`
so apparently i wasnt specifiying a specific tagged version of the theme properly. but i Don't know how to do it.

**Comment by pjaudiomv** [comment]
this is the resonse i go tform the developer of the theme
https://github.com/pmarsceill/just-the-docs/issues/26

seems there may not be a way to request to use a specific tagged version, so we either use our fork and only update it when we know theres no breaking change. idk.

**Comment by radius314** [comment]
This article has the correct syntax https://www.siteleaf.com/blog/remote-themes/

**Comment by pjaudiomv** [comment]
thank you I google many different things and couldn't find that, I need to up my google skills. Anyway my email could get added on build notices?

**Pull request merged**
