### PR TITLE
safely parse legacy data for bmlt 3

### PR DESCRIPTION
**Pull request by pjaudiomv**
bmlt 3.0 is not gonna have the crazy `#@-@#` delimiters so trying to account for that

### CODE REVIEW

**Comment by pjaudiomv** [comment]
Didn't realize code was disabled, this is not needed

**Comment by dgershman** [comment]
Yeah I have a branch to do some code cleanups.

**Comment by pjaudiomv** [comment]
> Yeah I have a branch to do some code cleanups.

no worries I was confused, took me a second to realize what was going on.

**Comment by dgershman** [comment]
The main reason that code was still around was because it was required to migrate people from 2.x to 3.x.

**Pull request closed without merging**
