### PR TITLE
allow for digit map overrides from service body configuration #385

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
@pjaudiomv can you give this a try when you get a chance?

**Comment by pjaudiomv** [comment]
I just tested this and it didn't work :( it also seemed to of then neglected my other service body setting as a result of it not working.


Screen Shot 2020-03-20 at 10 43 33 PM

**Comment by radius314** [comment]
what do you mean by not working?

**Comment by pjaudiomv** [comment]
hold

**Comment by pjaudiomv** [comment]
So its not changing the digit maping, and once i do set `digit_map_search_type` it then ignores my `custom_query` and `result_count_max` and gos to location gathering

**Pull request merged**
