### PR TITLE
Tomato Meeting Search enable by setting

### PR DESCRIPTION
**Pull request by spiritualtheory**
Simple tomato meeting search setting - separate from helpline routing

### CODE REVIEW

**Comment by radius314** [comment]
Can you add a bullet about this in the release notes?

**Comment by spiritualtheory** [comment]
Sure - under version 3.6?

**Comment by radius314** [comment]
Yes.

**Comment by radius314** [comment]
In addition please remove yap.iml and add to .gitignore.

**Comment by spiritualtheory** [comment]
Ok - will take care of this afternoon

**Pull request merged**
