### PR TITLE
remove php 7.*

### PR DESCRIPTION
**Pull request by dgershman**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
I think we want to update the release to not have the php version in it

**Comment by pjaudiomv** [comment]
so they are just yap-verion.zip again

**Comment by dgershman** [comment]
didn't we find version issues between 8.0 and 8.1?

**Comment by pjaudiomv** [comment]
> didn't we find version issues between 8.0 and 8.1?

I don't think so. I think we just need to do a composer install with 8.0 then commit the lock file and a composer install with 8.1 will work fine with that. we can leave the matrix for tests but remove for release

**Comment by pjaudiomv** [comment]
I have a bunch of different php base images here if helpful https://github.com/bmlt-enabled/ci-tools/blob/main/.github/workflows/docker-base.yml

so you can do the things like

`docker run -t --rm -v $(pwd):/code -w /code bmltenabled/bmlt-ci-base:8.0-latest composer install`

**Comment by dgershman** [comment]
@pjaudiomv updated this

**Review by pjaudiomv — APPROVED** [review]

**Pull request merged**
