### PR TITLE
fix for beta builds

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by radius314** [comment]
Whats this fixing?

**Comment by pjaudiomv** [comment]
beta builds not being tagged as pre-release, and the condition should be on the `on` option

**Comment by radius314** [comment]
Not seeing what you are saying.  They say pre release for me.

**Comment by pjaudiomv** [comment]
weird it def didnt just say Pre-release

**Comment by pjaudiomv** [comment]
id be curious if a non beta build gets tagged properly with this expression `!~ /beta/` I had to change it to `!= *beta*` to work properly for contacts-bmlt but thats using dplv2

**Pull request merged**
