### PR TITLE
matrix releases

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Review by dgershman — APPROVED** [review]

**Comment by dgershman** [comment]
Does it make sense to have an 8.1 release too?  Will it cause confusion with not having one?

**Comment by dgershman** [comment]
image

Looks like it's failing because once one version is created the release is considered there.

**Comment by pjaudiomv** [comment]
yea need to create the release in a single step and upload them in the matrix

**Comment by dgershman** [comment]
Or you might be able to set allowUpdates = true

**Pull request merged**
