### PR TITLE
query performance improvements

### LINKED ISSUE #284: query performance improvements
query only the fields that are needed, which will speed up root server responses.

### PR DESCRIPTION
**Pull request by pjaudiomv**
resolves #284

### CODE REVIEW

**Comment by radius314** [comment]
This looks mostly good.  However there are some applications which consume the Yap api that might need some additional data points.  Checkout https://github.com/bmlt-enabled/yap-bots and https://github.com/bmlt-enabled/yap-alexa-skill which call api.php, which in turn uses `getMeetings()`

**Comment by pjaudiomv** [comment]
My bad I squashed the commit, I guess that was silly before approving.

**Comment by pjaudiomv** [comment]
I added location info and province I believe

**Comment by radius314** [comment]
There seems to be some other values missing.

**Pull request merged**
