### PR TITLE
yap installer mvp

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
I did have one issue with the path, it was trying to send me up a previous level. maybe something with the rewrite rules.

**Comment by pjaudiomv** [comment]
this link https://nnerna.charlestonna.org/yap-wizard/ redirects to https://nnerna.charlestonna.org/admin/wizard.php

**Comment by pjaudiomv** [comment]
this was yesterday so havent tested latest commits

**Comment by radius314** [comment]
They have been significant changes since yesterday

**Comment by radius314** [comment]
> this link https://nnerna.charlestonna.org/yap-wizard/ redirects to https://nnerna.charlestonna.org/admin/wizard.php

Looking into this.

**Comment by radius314** [comment]
> > this link https://nnerna.charlestonna.org/yap-wizard/ redirects to https://nnerna.charlestonna.org/admin/wizard.php
> 
> Looking into this.

I pushed a change that I believe will solve this bug for you.

**Comment by pjaudiomv** [comment]
Was not able to test the latest change but looks good, can probably test tomorrow if you want to wait otherwise merge it

**Comment by radius314** [comment]
I will wait.

**Comment by pjaudiomv** [comment]
👍

**Pull request merged**
